# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cube <- function(prob, Xbal) {
    .Call('BalancedSampling_cube', PACKAGE = 'BalancedSampling', prob, Xbal)
}

lcube <- function(prob, Xspread, Xbal) {
    .Call('BalancedSampling_lcube', PACKAGE = 'BalancedSampling', prob, Xspread, Xbal)
}

lpm <- function(prob, x, h) {
    .Call('BalancedSampling_lpm', PACKAGE = 'BalancedSampling', prob, x, h)
}

lpm1 <- function(prob, x) {
    .Call('BalancedSampling_lpm1', PACKAGE = 'BalancedSampling', prob, x)
}

lpm2 <- function(prob, x) {
    .Call('BalancedSampling_lpm2', PACKAGE = 'BalancedSampling', prob, x)
}

rpm <- function(prob) {
    .Call('BalancedSampling_rpm', PACKAGE = 'BalancedSampling', prob)
}

sb <- function(p, x, s) {
    .Call('BalancedSampling_sb', PACKAGE = 'BalancedSampling', p, x, s)
}

scps <- function(prob, x) {
    .Call('BalancedSampling_scps', PACKAGE = 'BalancedSampling', prob, x)
}

spm <- function(prob) {
    .Call('BalancedSampling_spm', PACKAGE = 'BalancedSampling', prob)
}

vsb <- function(probs, ys, xs) {
    .Call('BalancedSampling_vsb', PACKAGE = 'BalancedSampling', probs, ys, xs)
}

